#define UART_INIT_OK 1

#define UART_SEND_OK 10
#define UART_SEND_WORD_ERROR 11
#define UART_READ_OK 12
#define UART_NOT_INITIALIZED 13
#define UART_SEND_STRING_ERROR 14

#define DHT_COMMON_ERROR 30
#define DHT_OK 31

#define IO_ERROR 40
#define IO_OK 41
#define ILLEGAL_PIN_NUMBER 42
